# This is appveyor yml configuration to tell
# what to do for each logical build/deployment phase: 
# all the options are here: https://www.appveyor.com/docs/appveyor-yml/

# we want disable the MSBuild
build: off

#Kick off the CI/CD pipeline
before_build:
#https://msdn.microsoft.com/en-us/powershell/wmf/5.1/install-configure 
 - echo "started"
 - ps: install-module invokebuild
 - echo "installed invokebuild module"
 - ps: import-module invokebuild
 - echo "imported invokebuild module"
 - ps: import-module sqlps
 - echo "imported sqlps module"

#define the build script instead of automated MSBuild 
build_script:
  - ps: invoke-build
